### ISSUE TITLE
Getting 404 page on sub pages

### ISSUE THREAD

**Issue by wp-coin** [lando/symfony#18]
home page loads fine but not sub pages example: http://localhost:32807/browse/api

lando.yml
```
name: symfony
recipe: symfony
config:
  webroot: public
  php: 8.1
```

version: symfony 6.2
windows wsl2
