### ISSUE TITLE
Incorrect volume path when using nginx volume override

### ISSUE THREAD

**Issue by ttk** [lando/symfony#61]
When adding an extra volume to the `appserver_nginx` container, the source directory on the host is wrong as it seems to be using the location of the underlying docker compose file location instead of my lando app root directory for the relative path.   Best demonstrated by example:

Simple lando config:
```
name: test
recipe: symfony
config:
  via: nginx

services:
  appserver_nginx:
    overrides:
      volumes:
        - ./vendor:/app/vendor
```

Expected bind mounts:
`%LANDO_APP_ROOT%/vendor:/app/vendor`

Actual bind mounts:
`%USERPROFILE%/.lando/compose/test:/app/vendor`

I tested the same scenario with the `nginx` lando plugin directly, and it mounted the expected directory, so I think it something to do with the way the symfony lando plugin integrates with nginx.

```
$ lando version
v3.21.2

$ lando version --component symfony
v1.6.1

$ lando version --component nginx
v1.2.0

$ lando version --component php
v1.3.0
```

OS: Windows 11 (not sure if that matters.
